### ISSUE TITLE
Complete vm-mock and its UT

### ISSUE THREAD

**Issue by Thykof** [massalabs/massa-as-sdk#116]
following https://github.com/massalabs/massa-as-sdk/pull/115#pullrequestreview-1225787059

how to:
- add missing ABI functions into vm-mock
- add unit test

Tasks:
- [x] #210
https://github.com/massalabs/massa-as-sdk/pull/220

**Coins**
- [x] #213
https://github.com/massalabs/massa-as-sdk/pull/214

**Execution**
- [x] #215
https://github.com/massalabs/massa-as-sdk/pull/218

**Account**
- [x] #216
https://github.com/massalabs/massa-as-sdk/pull/224

**Helpers**
- [x] #219
https://github.com/massalabs/massa-as-sdk/pull/221

**Operation Datastore**
- [x] #217
https://github.com/massalabs/massa-as-sdk/pull/223

**Comment by longgamma-massa** [comment]
@Thykof 'add mock for CallerHas....' done?

**Comment by Thykof** [comment]
Yes but still some mock to do but low priority because for now we do not need them.

**Comment by Ben-Rey** [comment]
All tasks Done
