### ISSUE TITLE
Import env.seed for "randomInt" function

### ISSUE THREAD

**Issue by nirnaeth-arnoediad** [massalabs/massa-as-sdk#12]
Tried to get a random integer with a simple sc but get an error after executed it on my node:

`Data: {"massa_execution_error":"Runtime error: runtime error when executing operation eFmzi8wuCGcvKZ1Rr1aF8jhV3EVTvAa8Nu3ZsTwziBew77QCi: Runtime error: bytecode execution error: RuntimeError: Error while importing \"env\".\"seed\": unknown import. Expected Function(FunctionType { params: [], results: [F64] })\n    at <unnamed> (<module>[5]:0x218)"}`

Looks like it requires an env.seed import that is mentioned inside the error (`Expected Function(FunctionType { params: [], results: [F64] })`). But how?

An example approach by assemblyscript official book:
`function env.seed?(): f64`

Another example approach by @gregLibert :
```
imports!{
    "env" => {
        "seed" => <a determinist random function>,
    },

};
```
and finally my code called by main:
```
import { generateEvent } from "@massalabs/massa-sc-std";
import { randomInt } from "@massalabs/as";

export function randomWinner(_args: string): void {

    const a = randomInt(1, 10);
    generateEvent("Number: " + a.toString());

}
```
Any ideas?

**Comment by gregLibert** [comment]
As explained [here](https://www.assemblyscript.org/concepts.html#special-imports), AssemblyScript expects special imports provided by the running environment.

At least, the three following functions should exist:
- function env.abort?(message: usize, fileName: usize, line: u32, column: u32): void
- function env.trace?(message: usize, n: i32, a0..4?: f64): void
- function env.seed?(): f64

**Comment by qdrn** [comment]
For now, what you can do is use the following code:
```ts
import { generateEvent, unsafeRandom } from "@massalabs/massa-sc-std";
import { randomInt } from "@massalabs/as";

export function randomWinner(_args: string): void {
    Math.seedRandom(unsafeRandom())
    const a = randomInt(1, 10);
    generateEvent("Number: " + a.toString());
}
```

Hope it helps you.

**Comment by AurelienFT** [comment]
env.seed has been implemented cc @gregLibert

**Comment by Thykof** [comment]
so we should be able to use the `random` function provide by assembly script https://www.assemblyscript.org/stdlib/math.html#variants

**Comment by qdrn** [comment]
Can we close this one ? I think there was a bug in the end. What's the status ?

**Comment by Thykof** [comment]
I'll create a page in Massa-In-Action ^^ to show case and be sure it works as expected
