### ISSUE TITLE
Share a same linter for AS

### ISSUE THREAD

**Issue by SlnPons** [massalabs/massa-as-sdk#130]
blocked by https://github.com/massalabs/massa-as-sdk/issues/57

# Scope
- [ ]  https://eslint.org/docs/latest/developer-guide/shareable-configs
- [ ] take the eslintrc.cjs of the sdk

**Comment by 0xMazout** [comment]
Sharable config is created in this repo : https://github.com/massalabs/eslint-config

Now we will deploy it on each repo
