### ISSUE TITLE
Having two different template type for Storage

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa-as-sdk#135]
I just saw that you changed the way you accept parameter for functions like `Storage.set` and make the type conversions in the library. 

Wouldn't be nice to have a different template for key and value ?

Because sometime I might want to explicit my key (because the storage cost of a key is fix and I want code readibility) but not my value.

Right now I'm forced to do : 
```
Storage.set<StaticArray<u8>>(toBytes("key), test);
```

It would be nice that I can just make : 
```
Storage.set("test", test);
```

**Comment by Thykof** [comment]
duplicated with https://github.com/massalabs/massa-as-sdk/issues/136
