### ISSUE TITLE
Divide tests into different categories: black/white box, code sample tests

### ISSUE THREAD

**Issue by Ben-Rey** [massalabs/massa-as-sdk#171]

**Comment by Ben-Rey** [comment]
@gregLibert can we close this one as it is not relevant for this repository

**Comment by gregLibert** [comment]
@Ben-Rey in fact we can do it, but this will need to update the code.

For example, the function [toDatastoreFormat](https://github.com/massalabs/massa-as-sdk/blob/main/assembly/std/storage.ts#L11) is not testable today.

To change that, we need to:
- export it (if not, as-pect won't be able to access it)
- create unit-tests by directly referencing the file storage.ts in the "storage_black-box_spec.ts" file
- change the ways [index.ts exports storage functions](https://github.com/massalabs/massa-as-sdk/blob/main/assembly/std/index.ts#L7) for the users of this package to be sure that toDatastoreFormat is not exported.

**Comment by gregLibert** [comment]
doesn't make a lot of sens for this lib. We will see with AS package
