### ISSUE TITLE
Module '~lib/@massalabs/as-types' has no exported member 'Serializable'

### ISSUE THREAD

**Issue by litchipi** [massalabs/massa-as-sdk#178]
Encountered while building a unit test for https://github.com/massalabs/massa-unit-tests-src/pull/33

**Describe the bug**
When building a WASM using this package as a dependency, this error prevents the building from completing:
```
> build:rt:basic_main
> asc assembly/massa-sc-runtime/basic_main.ts --target release --exportRuntime --runtime stub --outFile build/massa-sc-runtime/basic_main.wasm

ERROR TS2305: Module '~lib/@massalabs/as-types' has no exported member 'Serializable'.
   :
 1 │ import { Valider, Serializable, Args, Result } from '@massalabs/as-types';
   │                   ~~~~~~~~~~~~
   └─ in ~lib/@massalabs/massa-as-sdk/assembly/std/address.ts(1,19)

ERROR TS2304: Cannot find name 'Serializable'.
   :
 7 │ export class Address implements Valider, Serializable {
   │                                          ~~~~~~~~~~~~
   └─ in ~lib/@massalabs/massa-as-sdk/assembly/std/address.ts(7,42)

FAILURE 2 compile error(s)
ERROR: "build:rt:basic_main" exited with 1.
ERROR: "build_rt" exited with 1.
```

**To Reproduce**

1. Clone https://github.com/massalabs/massa-unit-tests-src
2. Checkout branch `tim/validate_address`
3. Run `npm run build`

**Expected behavior**
Compilation should complete

**Version**
On commit `1a0f1925ec758b007f85e4935fef0a61d602e9c8` (latest as of creation of unit test)

**Comment by Ben-Rey** [comment]
The fix has been completed on this branch: https://github.com/massalabs/massa-unit-tests-src/tree/tim/validate_address_fix. The "@massalabs/massa-as-sdk" and "@massalabs/as-types" packages needed to be updated, and I also updated deprecated functions as a result of the package updates.

To test the fix :
```
npx clear-npx-cache
npm install
npm run build
```
