### ISSUE TITLE
Few problems in the documentation

### ISSUE THREAD

**Issue by windushka** [massalabs/massa-as-sdk#180]
There are a few problems regarding the following functions:
createSC : 

```
createSC(bytecode: StaticArray<number>): address

Creates a new smart contract.

Take a base64 string representing the module binary and create an entry in the ledger.

The context allow you to write in this smart contract while you're executing the current bytecode.

```
The problem here is that this function does not take a string as an argument but rather a byteArray maybe?

```Takes a byteArray? representing the binary module and creates an entry in the ledger.```

fileToByteArray:

```
fileToByteArray(filePath: string): StaticArray<u8>
Convert given file content to byteArray.

Note: this function shall never be called but is dynamically replace using byteArray transformer. More info here:

```

Missing more info and syntax problems.
It would be correct to say ``` Note: this function shall never be called, it is dynamically replaced using the byteArray converter. More info here:```

**Comment by Ben-Rey** [comment]
Thanks for the remark, this will be fixed in https://github.com/massalabs/massa-as-sdk/issues/194

**Comment by Ben-Rey** [comment]
Done in https://github.com/massalabs/massa-as-sdk/issues/194
