### ISSUE TITLE
get function in vm.js returns empty value instead of throwing error when data entry not found

### ISSUE THREAD

**Issue by Ben-Rey** [massalabs/massa-as-sdk#184]
Context
The get function in our blockchain smart contract SDK is supposed to return the value associated with the provided key. However, if there is no value associated with the key, it throw an error from the node ( Runtime error: data entry not found" ), but currently, the test vm mock is returning an empty value instead.

**User flow**
As a user of our SDK, when calling the get function with a key, I expect to receive the value associated with that key in the datastore. If there is no value associated with the key, I expect the function to throw an error so that I can handle it accordingly.

**How to**
To fix this issue, we need to update vm assembly_script_get_data and assembly_script_get_data_for functions to throw an error when there is no value associated with the provided key. The following are the steps to be taken:

Identify the location in the assembly_script_get_data_for function where the empty value is returned.
Update the function to throw an error with a message "Runtime error: data entry not found" when an empty value is returned.
Test the updated function to ensure it throws the correct error when there is no value associated with the provided key.

**QA testing**
Yes, this task requires QA tests. To validate the fix, we can write unit tests for the get function that test its behavior when there is a value associated with the key and when there is no value associated with the key. The tests should check that the function returns the correct value when there is a value associated with the key and throws the correct error when there is no value associated with the key.

**Comment by gregLibert** [comment]
@Ben-Rey What is the error message returned by the node when you try to access a non existing key ?

**Comment by Ben-Rey** [comment]
> @Ben-Rey What is the exact error message returned by the node when you try to access a non existing key ?

I updated the issue, it's :
Runtime error: data entry not found"

**Comment by Ben-Rey** [comment]
We also need to check if we have the same problem on the getOf function with the address because at the moment if we provide an address that does not exist, we will also have an error from the node. Here is the complete log of the error: 

"{\"massa_execution_error\":\"Runtime error: runtime error when executing operation O12LQTL8kkq2Vzaos1tbKAdFSbhzCZL15vVLdCbzy3mgBgFXxWWE: Runtime error: module execution error in execute_executesc_op: RuntimeError: Runtime error: RuntimeError: Runtime error: address parsing error: AS1PHDyEuJrTKVd6PjssBEX15DRVh7u2M7162U529VxWYeiRKUZa\"}"

**Context**
I deploy a contract that call getOf in the constructor with a fake address
