### ISSUE TITLE
Fungible token - mint/burn

### ISSUE THREAD

**Issue by gregLibert** [massalabs/massa-as-sdk#19]
Add mint/burn functionalities to MassaLabs Fungible token implementation.

**Comment by peterjah** [comment]
@gregLibert 
I think mintable ability for a token has not so much value without the ability to set a "Minter Role" for an address.
 it corresponds to the "Ownable" contract attribute in openzeppelin.
So i am thinking to implement a basic role management (basically a minter role setter function)?
And the burn function is basically sending coins to 0x0000....

Are we agree  on that ?

**Comment by Thykof** [comment]
There is an open PR about this feature here https://github.com/massalabs/massa-as-sdk/pull/27

**Comment by Trottoir** [comment]
New issue on right repo => https://github.com/massalabs/massa-sc-contracts/issues/4

**Comment by Trottoir** [comment]
BLOCKED => Waiting for https://github.com/massalabs/massa-as-sdk/issues/17 to be reviewed

**Comment by Thykof** [comment]
Are we going to put mint/burn in massa-as-contracts?

**Comment by Trottoir** [comment]
They are in [massa](https://github.com/massalabs/massa-sc-contracts/pull/5)
