### ISSUE TITLE
Implement is_valid function in address Class

### ISSUE THREAD

**Issue by Ben-Rey** [massalabs/massa-as-sdk#195]
Currently we do not have a correct address validation in the address class. We should use the is_valid function of sc-runtime.

Related to: https://github.com/massalabs/massa-sc-runtime/issues/142

**Comment by gregLibert** [comment]
This function should be remove from this class I think. We should also do the same with valider interface.

The address validity check should be impelmented somewhere else.

**Comment by gregLibert** [comment]
@Ben-Rey  can we sync on this ?
