### ISSUE TITLE
Incorporate sc-std in this package

### ISSUE THREAD

**Issue by gregLibert** [massalabs/massa-as-sdk#2]
- [x] Migrate massa-sc-std to this repo.
- [ ] Add an issue on massa-sc-std to update the readme to reference this new project
- [x] Add an issue on massa-sc-std to delete the repo after some time: https://github.com/massalabs/massa-sc-std/issues/44

**Comment by Thykof** [comment]
Only one sub-task remaining, and maybe we should transfer open issues of std into this sdk
