### ISSUE TITLE
Fungible token - vote

### ISSUE THREAD

**Issue by gregLibert** [massalabs/massa-as-sdk#20]
Add vote functionality to MassaLabs Fungible token implementation.

**Comment by Trottoir** [comment]
What do you mean by a vote functionnality ? 

I know about the Voting Escrow ( Voting power decreasing linearly with time ) but I'm not sure that this is what we mean in that ticket no ?

**Comment by 0xMazout** [comment]
Currently diving into this project. if you have any time to explain what is needed @gregLibert It would be cool

**Comment by gregLibert** [comment]
This is what I have in mind : https://docs.openzeppelin.com/contracts/4.x/api/token/erc20#ERC20Votes

If it doesn't make sens, let's talk about it :-)

**Comment by 0xMazout** [comment]
The main goal is to implement all of this func 


![Image](https://user-images.githubusercontent.com/10938862/200624176-ce9ae1d6-1304-457a-9183-075217657070.png)


For this we will need an equivalent implementation of all of this 



![Image](https://user-images.githubusercontent.com/10938862/200624308-10dd0ad1-8238-448e-b0c9-f02411acb84a.png)

**Comment by gregLibert** [comment]
> For this we will need an equivalent implementation of all of this

ERC20 functions should be there but ERC20PERMIT is missing.

The need around the "private" functions of EIP712 is to clarify.

**Comment by 0xMazout** [comment]
> 

The Erc 20 Permit has been build 5days ago and his first release has been release 5 days ago.

Shall we consider this right now ? or maybe it's to fresh to build on it ?

**Comment by 0xMazout** [comment]
https://eips.ethereum.org/EIPS/eip-2612

5days ago was the launch of EIP2612

**Comment by 0xMazout** [comment]
From EIP2612
![image](https://user-images.githubusercontent.com/10938862/200798439-240e500a-7859-4425-ae2e-98cb1a82701b.png)

**Comment by 0xMazout** [comment]
After Discussion we decided, to cut the crap atm, and don't implement eip2612 and eip712.

So my point is to understand clearly how as sdk work

And right now i have to understand and transpile ERC 20 Votes function,  from Solidity to AS .

I think it can take some time and i will proceed by iteration digging on each functions what is really needed and what we actually get done on the sdk

**Comment by 0xMazout** [comment]
Checkpoints :


![Image](https://user-images.githubusercontent.com/10938862/200847838-6bcfd184-63b2-4701-b772-0c0a73491b45.png)


Is it relevant to our votes systems ? 
In the process of building Massa it is done at the good time ?
And does it fit to our Massa context ( in ETH , Checkpoints are storing values at each block )

**Comment by 0xMazout** [comment]
Delegate : there is three distinct mecanism , 
- delegate(sender, delegatee) 
- delegateBySig(same as delegate with signer) 
- _delegate  (change delegator to delegatee)

_delegate will involve moveVotingPower which involve the Checkpoints concepts (Maybe we can bypass This, have to discuss)

**Comment by 0xMazout** [comment]
Trade Off : 
- Avoiding EIP 712
- Avoiding EIP 2612
- Implementation off Checkpoints to grab past data --> Reported to V2
- Implementation only Owner Hardcoded --> Dynamic implementation Reported Later

Potential technical implementation : Todo

**Comment by 0xMazout** [comment]
Lists of implementations : 
Governance subjects //
- CRUD Proposal 
- voting Delay , voting Period (Based on date/timestamp not , Period , atm no link between data on chain and sdk )
- executeProposal
- And lots of events : castVote , ProposalsExecuted, Proposals Created , Proposals canceled

Token Context subject //
- Delegate 
- Mint (Currently implemented by Eugeny still in review) Think to overcharge it to fit with the voting system 
- Burn (Not implemented atm)
- Update Voting power

Voting action//
- Vote to a proposal 
??

ATM that what i have identified maybe will find something else after some implementation
If you have any concerns feel free to reach me

**Comment by 0xMazout** [comment]
https://github.com/massalabs/massa-as-sdk/issues/37
