### ISSUE TITLE
Mock all external functions

### ISSUE THREAD

**Issue by Ben-Rey** [massalabs/massa-as-sdk#201]
- [X] assembly_script_local_call
- [X] assembly_script_local_execution
- [X] assembly_script_get_bytecode_for
- [X] assembly_script_function_exists
- [X] assembly_script_get_remaining_gas
- [x] assembly_script_delete_data_for
- [x] assembly_script_append_data
- [x] assembly_script_append_data_for
- [x] assembly_script_get_owned_addresses
- [X] assembly_script_transfer_coins
- [x] assembly_script_transfer_coins_for
- [x] assembly_script_get_balance
- [x] assembly_script_get_balance_for
- [x] assembly_script_get_call_coins
- [x] assembly_script_signature_verify
- [x] assembly_script_address_from_public_key
- [x] assembly_script_send_message
- [x] assembly_script_get_current_period
- [x] assembly_script_get_current_thread
- [x] assembly_script_set_bytecode
- [x] assembly_script_set_bytecode_for
- [x] assembly_script_get_op_keys
- [x] assembly_script_has_op_key
- [x] assembly_script_get_op_data

**Comment by Elli610** [comment]
@Ben-Rey The assembly_script_get_owned_addresses is not referenced in the assembly/env/env.ts file.  So how do we implement it and if so, how? (inputs, outputs, ...)
