### ISSUE TITLE
Sdk new architecture

### ISSUE THREAD

**Issue by 0xSwapFeeder** [massalabs/massa-as-sdk#222]
**Context**
The std/index.ts file is a mess, we need to split functions in separate modules.

**User flow**
At the end we should have a clear vision of the different sdk functionalities so that the user  is not lost in the documentation.

**How to**
To do so, we need also to have clear module descriptions/documentation.
Here is a new architecture idea, let's discuss about it !
Then, lets implement/split functionalities.

# Index Splitting Ideas

## datastore.ts:
Operation Datastore functions
- derKeys
- getNumberOfKeys
- getKeysOf
- getKeys
- getOpKeys
- getOpData
- hasOpKey

## calls.ts:
Smart-Contract call functions + utilities (callerHasWriteAccess)
- functionExists
- callerHasWriteAccess ?
- localExecution
- localCall
- call
- sendMessage

## bytecode.ts:
Bytecode manipulation functions
- createSC
- getBytecodeOf
- getBytecode
- callerHasWriteAccess ?

## transfer.ts / balance.ts / coins.ts:
Balance and transfer functions
- transferCoins
- transferCoinsOf
- balance
- balanceOf

## encryption.ts / convert.ts:
Conversion functions
- sha256
- fileToByteArray
- unsafeRandom
- toBase58
- isSignatureValid

## Move to address.ts ?
- publicKeyToAddress
- validateAddress

## Move to context.ts ?
- currentPeriod
- currentThread

## Leave into index.ts ?
- print
- generateEvent
- createEvent

**Comment by 0xSwapFeeder** [comment]
#208 needs to be merged first ofc.

**Comment by Ben-Rey** [comment]
All modules will be exported from the index as before, which should not change anything from the user's point of view.

**Comment by 0xSwapFeeder** [comment]
I'm just not sure if there is a difference between Keys functions and OpKeys functions, don't they manipulate the same storage ? Otherwise that's looking nice, lgtm :+1:
