### ISSUE TITLE
Remove as-pect from massa-as-sdk and replace it with envy

### ISSUE THREAD

**Issue by BatiGencho** [massalabs/massa-as-sdk#25]
Currently as-pect is still inside the massa-as-sdk repo and is creating issues because of the asterster.imports.js to create and run as-pect tests. We need to remove it and replace it with envy and transfer all the tests into envy format.

**Comment by gregLibert** [comment]
After discussin this with the AS community, we will go back to as-pect which is now working properly.

**Comment by SlnPons** [comment]
@longgamma-massa just saw this ticket in QA. Maybe it relates to you.
