### ISSUE TITLE
Changes params sendMessage

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa-as-sdk#305]
Change the params names of `sendMessage` so that it's more intuitive. We already made the change in [massa](https://github.com/massalabs/massa/blob/fa546c26e8066be1a043db50ddab058519659693/massa-async-pool/src/message.rs#L274)

**Comment by damip** [comment]
@AurelienFT can you make a PR on this ?

**Comment by AurelienFT** [comment]
@damip yes but can I have the permissions to push on this repository please
