### ISSUE TITLE
U64 Subtraction Overflow Error

### ISSUE THREAD

**Issue by icegriffinguru** [massalabs/massa-as-sdk#350]
**Describe the bug**
I accidently subtracted `10^9` from `0u64` and it did not throw an error but returned `2^64 - 10^9`.

**Suggest**
Is there a way implementing SafeMath operation to check math overflows?

**Comment by Ben-Rey** [comment]
I think what you need is: https://github.com/massalabs/as/blob/193a8f5d77d0a9c99c1aad9141c62a5489cd0e9c/packages/as-types/assembly/safeMath.ts#L13
