### ISSUE TITLE
Update Args class serialisation process with byte arrays

### ISSUE THREAD

**Issue by ASAPSegfault** [massalabs/massa-as-sdk#77]
**Context**
As of testnet 17, parameters sent to smart contract are now byte arrays and not strings anymore
The args class serialise data into a string, it needs to be updated to match the new standard.

**How to** 
- The Args class must serialise data in byte arrays instead of strings
- The Args class must deserialise data from a byte array instead of a string

Technical details:
- To be added

**Comment by Thykof** [comment]
I think it's already solved by https://github.com/massalabs/massa-as-sdk/pull/39

**Comment by ASAPSegfault** [comment]
Indeed it looks like so. Closing the issue.
