### ISSUE TITLE
Add a result object

### ISSUE THREAD

**Issue by gregLibert** [massalabs/massa-as-sdk#84]
like [here](https://github.com/lunatic-solutions/as-lunatic/blob/ab7c18143874487e8c00cb012771e2511167f44a/assembly/error/index.ts#L86-L110).

**Comment by Thykof** [comment]
Should we use Result object of as? https://github.com/massalabs/as/pull/38/files#diff-2b7601b6d171e98e9333ad956633aab9c2c9a0e8adb6187dc0b56fe7fcca80f8

**Comment by gregLibert** [comment]
You're right, will be handled in massalabs/as#38
