### ISSUE TITLE
Allow to use string as key on abi functions

### ISSUE THREAD

**Issue by Trottoir** [massalabs/massa-as-sdk#86]
Change signature of key/value pair for storage functions : 
FROM : 
- StaticArray<u8>
TO : 
- StaticArray<u8> | string

This will reduce the amount of code in smart contracts for converting values

**Comment by gregLibert** [comment]
@Trottoir I'm not sure we can define a type as StaticArray or string in AS. Can you verify that ?
If not, what are the work around ?

**Comment by Trottoir** [comment]
> @Trottoir I'm not sure we can define a type as StaticArray or string in AS. Can you verify that ?

Yeap indeed it's completly impossible I tried it & replace it with the generic type <T>

This is one workaround, OR duplicate functions : 
- set <=> setString
- setOf <> setStringOf
(....)

**Comment by Thykof** [comment]
I think generic type is the best way to do this, but the way it is currently implemented in the open PR may be improved

here is a comment I posted:

*Warning: those functions will now accept any types, so if you provide i32 for example, it will take StaticArray<u8>(0). This change the behavior because before, passing i32 would not compile*

**Comment by Thykof** [comment]
Update: not being rejected by the compiler is a problem. So we will implement `setString` elsewhere.

**Comment by gregLibert** [comment]
> Update: not being rejected by the compiler is a problem. So we will implement `setString` elsewhere.

Maybe not anymore, thanks to your question here : https://discord.com/channels/721472913886281818/1047897635018780682

**Comment by gregLibert** [comment]
I have expanded this issue in order to manage both:
- strings,
- args, and
- staticArray<u8>
